## 1. Getting and Knowing your data

In [29]:
import pandas as pd
#pd.read_csv(filepath_or_buffer="school_students_test_data_100.csv")
student_marks = pd.read_table(filepath_or_buffer="school_students_test_data_100.csv",sep=",")
student_marks["Cut_off"] = (student_marks["Maths"]+student_marks["Science"])/2
#student_marks[["Student_Name","Cut_off","Average"]].sort_values(by= "Cut_off", ascending = False).filter_values(["Cut_off"]>89)
student_marks.loc[(student_marks["Cut_off"]> 85) & (student_marks["Average"]>70) , ["Student_ID","Student_Name", "Cut_off","Average"]].sort_values(by="Cut_off", ascending=False).head(10)

   Student_ID Student_Name  Cut_off  Average
77     STU078         Riya     91.0     71.4
94     STU095      Vignesh     91.0     85.4
14     STU015        Rahul     90.0     75.0
28     STU029       Harish     89.5     85.0
75     STU076      Bhavana     89.0     70.2
21     STU022        Anika     86.5     73.6

## 1.1 Perform initial analysis

In [ ]:
student_marks.shape
student_marks.isnull().sum()
student_marks.describe(include="all")

## 1.2 Find out the the marks

In [44]:
student_marks.nunique()

Student_ID          100
Student_Name         96
Marks                44
Maths                44
Science              46
English              46
Social_Science       45
Computer_Science     45
Total_Marks          70
Average              70
dtype: int64

## 1.3 Get top 5 list

In [58]:
student_marks.groupby(by="Maths")["Student_Name"].count().sort_values(ascending = False).head(10)

Maths
59    5
50    5
62    5
51    4
85    4
96    3
46    3
92    3
83    3
89    3
Name: Student_Name, dtype: int64

## 1.3 Get least5 list

In [60]:
student_marks.groupby(by="Maths")["Student_Name"].count().sort_values(ascending = True).head(10)

Maths
45    1
94    1
91    1
84    1
81    1
77    1
73    1
61    1
60    1
71    1
Name: Student_Name, dtype: int64

## 2. Data cleaning

In [2]:
student_marks.sort_values(by="Average",ascending=False).head(10)

,Student_ID,Student_Name,Marks,Maths,Science,English,Social_Science,Computer_Science,Total_Marks,Average
94,STU095,Vignesh,89.0,89,93,95,70,80.0,427,85.4
28,STU029,Harish,NaN,89,90,91,74,81.0,425,85.0
96,STU097,Sathish,86.0,86,77,96,81,72.0,412,82.4
10,STU011,Rohan,88.0,88,80,94,86,58.0,406,81.2
92,STU093,Ramesh,87.0,87,61,75,88,92.0,403,80.6
62,STU063,Ashwin,69.0,69,88,59,95,92.0,403,80.6
11,STU012,Meera,92.0,92,59,78,86,87.0,402,80.4
55,STU056,Vaishnavi,61.0,61,93,86,95,64.0,399,79.8
19,STU020,Riya,58.0,58,97,98,60,86.0,399,79.8
32,STU033,Surya,73.0,73,76,93,96,58.0,396,79.2

In [3]:
student_marks

,Student_ID,Student_Name,Marks,Maths,Science,English,Social_Science,Computer_Science,Total_Marks,Average
0,STU001,Aarav,85.0,85,55,98,51,47.0,336,67.2
1,STU002,Aadhya,52.0,52,79,85,87,84.0,387,77.4
2,STU003,Arjun,46.0,46,91,77,72,50.0,336,67.2
3,STU004,Ananya,92.0,92,60,83,67,71.0,373,74.6
4,STU005,Aditya,62.0,62,55,57,72,87.0,333,66.6
...,...,...,...,...,...,...,...,...,...,...
95,STU096,Ramya,88.0,88,56,75,52,90.0,361,72.2
96,STU097,Sathish,86.0,86,77,96,81,72.0,412,82.4
97,STU098,Madhumitha,49.0,49,51,71,60,80.0,311,62.2
98,STU099,Kishore,83.0,83,85,57,82,45.0,352,70.4
99,STU100,Aparna,85.0,85,64,51,83,52.0,335,67.0

In [5]:
student_marks.describe().sum()

Marks                537.836684
Maths                539.061626
Science              546.342971
English              541.925154
Social_Science       535.297500
Computer_Science     535.151528
Total_Marks         2237.449879
Average              527.489976
dtype: float64

In [7]:
import pandas as pd
student_marks_1 = {"Subject":["Lang1","Lang2","Maths","Science","SScience","CS"], 
"Marks":[99,98,96,98,98,87],
"Comments":["ABc","hn","jhjh","ccc","mnbd","fajdf"],
"Teacher":["Sir1","Sir22","Madam1","Madam2","Sir3","Madam3"]}
pd.DataFrame(student_marks_1)

    Subject  Marks Comments Teacher
0     Lang1     99      ABc    Sir1
1     Lang2     98       hn   Sir22
2     Maths     96     jhjh  Madam1
3   Science     98      ccc  Madam2
4  SScience     98     mnbd    Sir3
5        CS     87    fajdf  Madam3

## 3. How to deal with missing data

In [30]:
student_marks

,Student_ID,Student_Name,Marks,Maths,Science,English,Social_Science,Computer_Science,Total_Marks,Average,Cut_off
0,STU001,Aarav,85.0,85,55,98,51,47.0,336,67.2,70.0
1,STU002,Aadhya,52.0,52,79,85,87,84.0,387,77.4,65.5
2,STU003,Arjun,46.0,46,91,77,72,50.0,336,67.2,68.5
3,STU004,Ananya,92.0,92,60,83,67,71.0,373,74.6,76.0
4,STU005,Aditya,62.0,62,55,57,72,87.0,333,66.6,58.5
...,...,...,...,...,...,...,...,...,...,...,...
95,STU096,Ramya,88.0,88,56,75,52,90.0,361,72.2,72.0
96,STU097,Sathish,86.0,86,77,96,81,72.0,412,82.4,81.5
97,STU098,Madhumitha,49.0,49,51,71,60,80.0,311,62.2,50.0
98,STU099,Kishore,83.0,83,85,57,82,45.0,352,70.4,84.0
99,STU100,Aparna,85.0,85,64,51,83,52.0,335,67.0,74.5

In [6]:
import pandas as pd1
emp_Details = pd1.read_table(filepath_or_buffer="employee_test_data_100.csv",sep=",")
emp_Details

,Employee_ID,Employee_Name,Department,Job_Title,Age,Experience_Years,Salary_INR,City,Performance_Score,Years_in_Company
0,EMP001,Arun Rao,IT,Engineer,54,17,1657272,Bengaluru,4.7,15
1,EMP002,Priya Singh,Marketing,Team Lead,48,19,1448843,Madurai,4.4,10
2,EMP003,Karthik Das,Sales,Analyst,22,20,469289,Bengaluru,3.2,2
3,EMP004,Ananya Krishnan,Sales,Executive,53,22,958994,Pune,3.5,6
4,EMP005,Rahul Pillai,HR,Senior Engineer,54,21,460054,Delhi,2.7,9
...,...,...,...,...,...,...,...,...,...,...
95,EMP096,Aishwarya Iyer,Operations,Senior Engineer,30,18,1722899,Delhi,3.4,11
96,EMP097,Vijay Reddy,Sales,Team Lead,34,5,1572493,Hyderabad,4.3,3
97,EMP098,Pooja Patel,Operations,Team Lead,25,22,372401,Mumbai,4.5,14
98,EMP099,Rohan Nair,Finance,Analyst,39,18,1753222,Delhi,2.8,3
99,EMP100,Swetha Menon,Finance,Manager,25,25,689303,Hyderabad,3.5,10